### ISSUE TITLE
classnames-to-clsx: failed while fetching with 403 error

### ISSUE THREAD

**Issue by pjonsson** [codemod-com/commons#11]
If I run `codemod classnames-to-clsx lib` inside the node:20 docker container, I get this error message:
```
Error: Cannot spawn a message bus without a machine-id: Unable to load /var/lib/dbus/machine-id or /etc/machine-id: Failed to open file “/var/lib/dbus/machine-id”: No such file or directory

Codemod CLI uses "keytar" to store your credentials securely.
Please make sure you have "libsecret" installed on your system.
Depending on your distribution, you will need to run the following command
Debian/Ubuntu: sudo apt-get install libsecret-1-dev
Fedora: sudo dnf install libsecret
Arch Linux: sudo pacman -S libsecret

If you were not able to install the necessary package or CLI was not able to detect the installation please reach out to us at our Community Slack channel.
You can still use the CLI with file-based replacement that will store your credentials at your home directory.
Both positional and argument target options are passed. Defaulting to the argument target option...
✖ Fetching "classnames-to-clsx"...

Error while fetching codemod classnames-to-clsx: Error: Request failed with status code 403
```

Despite what the second error message says, I have installed libsecret-1-dev in the container, and I can run other codemods, so not sure why this one doesn't work.

**Comment by alexbit-codemod** [comment]
Thanks for reporting this issue. This codemod was created by @AlexMeah, but I noticed there’s no Git URL in the metadata of his published codemod in the `.codemodrc.json` file, meaning it’s not open source yet. We’ll need Alex’s help to reproduce the issue. 

Alex, could you please update the `.codemodrc.json` file and include the Git URL? Here’s a [sample](https://github.com/codemod-com/commons/blob/github_action/codemod-com/update-git-urls/.codemodrc.json#L9) for reference. 

Once the issue can be reproduced and identified as a Codemod CLI problem, the appropriate place to report it would be our main monorepo: [Codemod](https://github.com/codemod-com/codemod). 

Pro tip: You can always run `npx codemod feedback` to be redirected to our GitHub issue page.

Closing this issue now. Thanks again to both of you for building codemods and reporting issues to make them better for everyone! 🍻

**Comment by pjonsson** [comment]
@alexbit-codemod I was instructed to report the error in this repository by someone who had enough permissions to close my PR in the codemod repository: https://github.com/codemod-com/codemod/pull/1414#issuecomment-2548827938

**Comment by AlexMeah** [comment]
@pjonsson I've updated the `.codemodrc.json` as outline in https://github.com/codemod-com/commons/issues/11#issuecomment-2551856306 if you want to try again

**Comment by alexbit-codemod** [comment]
@pjonsson Sorry for the confusion. 

We will remove all the codemod sources from codemod monorepo and move them here. And we will update our issue templates soon to prevent such confusion for future devs. 

In general, issues about codemods transforms should be reported to the person who created them. 

And for issues related to our platform and CLI should be reported in the codemod monorepo.

**Comment by alexbit-codemod** [comment]
@arybitskiy is this a known issue? I think I've seen this in other places. Linux and keytar issue.

**Comment by alexbit-codemod** [comment]
@AlexMeah can you ping me on slack : go.codemod.com/community
some files such as index.js and putout package is strange for me to see over there.  I can debug this with u if u want. 

@pjonsson lets look at Alex's codemod and just use the script directly to unblock yourself.
